### ISSUE TITLE
Change the default branch to master

### ISSUE THREAD

**Issue by archseer** [colemickens/niche#5]
Github now does it's thing where it inits the repository with a default `main` branch. All the code was pushed to `master` so it's not visible by default when opening the repository.

**Comment by colemickens** [comment]
This is intentional. This isn't ready yet.

**Comment by archseer** [comment]
I see, makes sense. I found it while looking at my options for a small self-hosted build cache so I'll definitely be keeping an eye. (👋  by the way, I've learned a lot from your nixcfg!)

**Comment by colemickens** [comment]
@archseer Nice to hear. If you want, feel free to kick the tires from the master branch. The README isn't perfectly aligned with the CLI options, but it's fairly straight-foward.

I'm manually testing with Azure, I'm adding automated tests for AWS/B2 and then I'll start getting ready to publicize this more.
